name: Rezilion Test GitHub Action
on: [push]
jobs:
  python-test:
    runs-on: ubuntu-latest
    container:
      image: dtwitch/python-test
    env:
     REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
     REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.9.0
        with:
          image_name: 'dtwitch/python-test'
          mode: 'start'
          command: python3 -c "from PIL import Image;import time;time.sleep(5)"
  

  rezilion-validate:
    needs: [python-test]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:6978c669

    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_RUN_REMEDIATE: true
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.9.0
        with:
          mode: 'validate'
